// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbNppikbIrGGSXDVJFgHyrqHUH75sqcts',
    appId: '1:183954312491:web:a607814726f0c50e87c96e',
    messagingSenderId: '183954312491',
    projectId: 'taskvideoplayer-6c4d5',
    authDomain: 'taskvideoplayer-6c4d5.firebaseapp.com',
    storageBucket: 'taskvideoplayer-6c4d5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxAzhtWCOe9RWHik38wY75Lxlvjjr9whU',
    appId: '1:183954312491:android:0c1c54b043bd20dc87c96e',
    messagingSenderId: '183954312491',
    projectId: 'taskvideoplayer-6c4d5',
    storageBucket: 'taskvideoplayer-6c4d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtHibWoApmdjnN25GI7J_DvBQzDgWIuBs',
    appId: '1:183954312491:ios:5eb22f8e05b4354e87c96e',
    messagingSenderId: '183954312491',
    projectId: 'taskvideoplayer-6c4d5',
    storageBucket: 'taskvideoplayer-6c4d5.appspot.com',
    iosBundleId: 'com.example.videoplayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtHibWoApmdjnN25GI7J_DvBQzDgWIuBs',
    appId: '1:183954312491:ios:435712fd8d48759587c96e',
    messagingSenderId: '183954312491',
    projectId: 'taskvideoplayer-6c4d5',
    storageBucket: 'taskvideoplayer-6c4d5.appspot.com',
    iosBundleId: 'com.example.videoplayer.RunnerTests',
  );
}
